# Generated by Django 3.2.9 on 2021-11-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(help_text='DNI Estudiante', max_length=8)),
                ('nombres', models.CharField(help_text='Nombres', max_length=191)),
                ('apellidos', models.CharField(help_text='Apellidos', max_length=191)),
            ],
            options={
                'verbose_name_plural': 'estudiantes',
            },
        ),
    ]
